name: PlayerResizer
main: sizer\Main
version: 1.2.6
author: [VMPE Development Team]
api:
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
load: STARTUP
commands:
  resize:
    usage: "/resize <size> [player]"
    description: "Allows a player to change their size"
    permission: "resize;resize.use;resize.other"
    alias: ["rs"]
permissions:
  resize:
    default: op
    children:
      resize.use:
        default: op
      resize.other:
        default: op
