name: ExplodingUnbreakables
main: jasonwynn10\EU\Main
version: 1.2.6
api:
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
description: "A plugin which allows for bedrock to be blown up after tnt explodes a certain number of times"
author: [VMPE Development Team]
