name: CrateChest
main: MysteryCrates\Main
api:
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
version: 4.0
author: [VMPE Development Team]
authors: ["ImagicalGamer", "iPeedro", "Day", "ID", "jasonwynn10"]
depend: EconomyAPI
