name: NoPvpFlight
main: jasonwynn10\NoPvpFlight\Main
author: [VMPE Development Team]
version: 1.2.6
api:
 - 3.0.0
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
description: "Stops a player's flight when they are attacked"
